name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:
  
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.x.x"

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Install dependencies
        run: msbuild src /t:Restore /p:Configuration=Release

      - name: Build
        run: msbuild src /p:Configuration=Release /p:Platform=x64
